/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package moviemanagementsystem;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class ActorGui extends javax.swing.JInternalFrame {

    Actor actor = new Actor();
    private DefaultTableModel model;

    /**
     * Creates new form ActorGui
     */
    public ActorGui() {
        initComponents();
        setTitle("Actors");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        fnLbl = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        dateOfBirth = new javax.swing.JTextField();
        miLbl = new javax.swing.JLabel();
        lnLbl = new javax.swing.JLabel();
        qoutes = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        actorTable = new javax.swing.JTable();
        addActorBtn = new javax.swing.JButton();
        updateActorBtn = new javax.swing.JButton();
        deleteActorBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.Color.white);
        setPreferredSize(new java.awt.Dimension(800, 470));

        backBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backBtn.setForeground(new java.awt.Color(51, 51, 51));
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moviemanagementsystem/images/back.png"))); // NOI18N
        backBtn.setText("BACK");
        backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        fnLbl.setBackground(new java.awt.Color(255, 255, 255));
        fnLbl.setForeground(new java.awt.Color(51, 51, 51));
        fnLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fnLbl.setText("First Name");

        name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));

        dateOfBirth.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dateOfBirth.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));

        miLbl.setBackground(new java.awt.Color(255, 255, 255));
        miLbl.setForeground(new java.awt.Color(51, 51, 51));
        miLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        miLbl.setText("Birth Date");

        lnLbl.setBackground(new java.awt.Color(255, 255, 255));
        lnLbl.setForeground(new java.awt.Color(51, 51, 51));
        lnLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lnLbl.setText("Quotes");

        qoutes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        qoutes.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fnLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(miLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lnLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(dateOfBirth, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                    .addComponent(qoutes, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fnLbl)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(miLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qoutes, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lnLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        actorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Birth Date", "Quotes"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        actorTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                actorTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(actorTable);
        if (actorTable.getColumnModel().getColumnCount() > 0) {
            actorTable.getColumnModel().getColumn(0).setResizable(false);
            actorTable.getColumnModel().getColumn(1).setResizable(false);
            actorTable.getColumnModel().getColumn(2).setResizable(false);
            actorTable.getColumnModel().getColumn(3).setResizable(false);
        }

        addActorBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addActorBtn.setForeground(new java.awt.Color(51, 51, 51));
        addActorBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moviemanagementsystem/images/add.png"))); // NOI18N
        addActorBtn.setText("ADD");
        addActorBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addActorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActorBtnActionPerformed(evt);
            }
        });

        updateActorBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        updateActorBtn.setForeground(new java.awt.Color(51, 51, 51));
        updateActorBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moviemanagementsystem/images/update.png"))); // NOI18N
        updateActorBtn.setText("UPDATE");
        updateActorBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateActorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActorBtnActionPerformed(evt);
            }
        });

        deleteActorBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        deleteActorBtn.setForeground(new java.awt.Color(51, 51, 51));
        deleteActorBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moviemanagementsystem/images/delete.png"))); // NOI18N
        deleteActorBtn.setText("DELETE");
        deleteActorBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteActorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActorBtnActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moviemanagementsystem/images/eraser.png"))); // NOI18N
        jButton1.setText("CLEAR");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(backBtn)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(updateActorBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                .addComponent(addActorBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                .addComponent(deleteActorBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addActorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(updateActorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteActorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void updateActorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActorBtnActionPerformed
        model = (DefaultTableModel) actorTable.getModel();

        if (actorTable.getSelectedRowCount() == 1) {
            String actorId = model.getValueAt(actorTable.getSelectedRow(), 0).toString();
            String actorName = name.getText();
            String actorBDate = dateOfBirth.getText();
            String actorQoute = qoutes.getText();
            //if current id is found, update movie
            if (actor.updateActor(actorId, actorName, actorBDate, actorQoute)) {
                //set updated value on table row
                model.setValueAt(actorId, actorTable.getSelectedRow(), 0);
                model.setValueAt(actorName, actorTable.getSelectedRow(), 1);
                model.setValueAt(actorBDate, actorTable.getSelectedRow(), 2);
                model.setValueAt(actorQoute, actorTable.getSelectedRow(), 3);
                JOptionPane.showMessageDialog(null, "Updated Successfully!");

                //reset field
                clearField();
            } else {

                JOptionPane.showMessageDialog(null, "Update failed!");
            }
        }

    }//GEN-LAST:event_updateActorBtnActionPerformed

    private void deleteActorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActorBtnActionPerformed
        int dialogResult = JOptionPane.showConfirmDialog(null, "Delete an Actor?", "Confirmation", JOptionPane.YES_NO_OPTION);

        model = (DefaultTableModel) actorTable.getModel();

        if (actorTable.getSelectedRowCount() == 1) {
            if (dialogResult == JOptionPane.YES_OPTION) {
                // User clicked "Yes"
                model.removeRow(actorTable.getSelectedRow());

                JOptionPane.showMessageDialog(null, "Deleted successfully!");
            } else {
                // User clicked "No" or closed the dialog
                System.out.println("Actor not deleted");
            }

        } else {
            //if table has no data
            if (actorTable.getSelectedRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "Table is empty!");
                //if no row selected
            } else {
                JOptionPane.showMessageDialog(null, "Please select single row to delete!");
            }
        }
    }//GEN-LAST:event_deleteActorBtnActionPerformed

    private void actorTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actorTableMouseClicked
        model = (DefaultTableModel) actorTable.getModel();

        //set data to text field when selected
        String tableName = model.getValueAt(actorTable.getSelectedRow(), 1).toString();
        String tableBirthDate = model.getValueAt(actorTable.getSelectedRow(), 2).toString();
        String tableQoutes = model.getValueAt(actorTable.getSelectedRow(), 3).toString();

        //set to text field
        name.setText(tableName);
        dateOfBirth.setText(tableBirthDate);
        qoutes.setText(tableQoutes);
    }//GEN-LAST:event_actorTableMouseClicked

    private void addActorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActorBtnActionPerformed
        String actorName = name.getText();
        String actorBDate = dateOfBirth.getText();
        String actorQoute = qoutes.getText();

        if (actorName.equals("") || actorBDate.equals("") || actorQoute.equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill in all fields!");

        } else {

            actor.addActor(actorName, actorBDate, actorQoute);
            displayTable();

            JOptionPane.showMessageDialog(null, "Added Successfully!");

            //reset field
            clearField();

        }
    }//GEN-LAST:event_addActorBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        name.setText("");
        dateOfBirth.setText("");
        qoutes.setText("");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        actorTable.clearSelection();
    }//GEN-LAST:event_jButton1MouseClicked
    private void displayTable() {
        Object[] data = actor.displayActor();
        model = (DefaultTableModel) actorTable.getModel();
        model.addRow(data);
    }

    private void clearField() {
        name.setText("");
        dateOfBirth.setText("");
        qoutes.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable actorTable;
    private javax.swing.JButton addActorBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField dateOfBirth;
    private javax.swing.JButton deleteActorBtn;
    private javax.swing.JLabel fnLbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lnLbl;
    private javax.swing.JLabel miLbl;
    private javax.swing.JTextField name;
    private javax.swing.JTextField qoutes;
    private javax.swing.JButton updateActorBtn;
    // End of variables declaration//GEN-END:variables
}
