/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package moviemanagementsystem;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class DirectorGui extends javax.swing.JInternalFrame {

    Director director = new Director();
    private DefaultTableModel model;

    /**
     * Creates new form ActorGui
     */
    public DirectorGui() {
        initComponents();
        setTitle("Directors");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        fnLbl = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        dateOfBirth = new javax.swing.JTextField();
        miLbl = new javax.swing.JLabel();
        lnLbl = new javax.swing.JLabel();
        movies = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        directorTable = new javax.swing.JTable();
        addDirectorBtn = new javax.swing.JButton();
        updateDirectorBtn = new javax.swing.JButton();
        deleteDirectorBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.Color.white);
        setPreferredSize(new java.awt.Dimension(800, 470));

        backBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backBtn.setForeground(new java.awt.Color(51, 51, 51));
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moviemanagementsystem/images/back.png"))); // NOI18N
        backBtn.setText("BACK");
        backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        fnLbl.setBackground(new java.awt.Color(255, 255, 255));
        fnLbl.setForeground(new java.awt.Color(51, 51, 51));
        fnLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fnLbl.setText("First Name");

        name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));

        dateOfBirth.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dateOfBirth.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));

        miLbl.setBackground(new java.awt.Color(255, 255, 255));
        miLbl.setForeground(new java.awt.Color(51, 51, 51));
        miLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        miLbl.setText("Birth Date");

        lnLbl.setBackground(new java.awt.Color(255, 255, 255));
        lnLbl.setForeground(new java.awt.Color(51, 51, 51));
        lnLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lnLbl.setText("Movie");

        movies.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        movies.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fnLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(miLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lnLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(dateOfBirth, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                    .addComponent(movies, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fnLbl)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(miLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(movies, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lnLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        directorTable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        directorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Birth Date", "Movies"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        directorTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                directorTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(directorTable);
        if (directorTable.getColumnModel().getColumnCount() > 0) {
            directorTable.getColumnModel().getColumn(0).setResizable(false);
            directorTable.getColumnModel().getColumn(1).setResizable(false);
            directorTable.getColumnModel().getColumn(2).setResizable(false);
            directorTable.getColumnModel().getColumn(3).setResizable(false);
        }

        addDirectorBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addDirectorBtn.setForeground(new java.awt.Color(51, 51, 51));
        addDirectorBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moviemanagementsystem/images/add.png"))); // NOI18N
        addDirectorBtn.setText("ADD");
        addDirectorBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addDirectorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDirectorBtnActionPerformed(evt);
            }
        });

        updateDirectorBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        updateDirectorBtn.setForeground(new java.awt.Color(51, 51, 51));
        updateDirectorBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moviemanagementsystem/images/update.png"))); // NOI18N
        updateDirectorBtn.setText("UPDATE");
        updateDirectorBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateDirectorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDirectorBtnActionPerformed(evt);
            }
        });

        deleteDirectorBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        deleteDirectorBtn.setForeground(new java.awt.Color(51, 51, 51));
        deleteDirectorBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moviemanagementsystem/images/delete.png"))); // NOI18N
        deleteDirectorBtn.setText("DELETE");
        deleteDirectorBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteDirectorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDirectorBtnActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moviemanagementsystem/images/eraser.png"))); // NOI18N
        jButton1.setText("CLEAR");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBtn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(addDirectorBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(updateDirectorBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(deleteDirectorBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(14, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addDirectorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(updateDirectorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteDirectorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void addDirectorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDirectorBtnActionPerformed
        String directorName = name.getText();
        String directorBDate = dateOfBirth.getText();
        String directorMovies = movies.getText();

        if (directorName.equals("") || directorBDate.equals("") || directorMovies.equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill in all fields!");

        } else {

            director.addDirector(directorName, directorBDate, directorMovies);
            displayTable();

            JOptionPane.showMessageDialog(null, "Added Successfully!");

            //reset field
            clearField();

        }
    }//GEN-LAST:event_addDirectorBtnActionPerformed

    private void updateDirectorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDirectorBtnActionPerformed
        model = (DefaultTableModel) directorTable.getModel();

        if (directorTable.getSelectedRowCount() == 1) {
            String directorId = model.getValueAt(directorTable.getSelectedRow(), 0).toString();
            String directorName = name.getText();
            String directorBDate = dateOfBirth.getText();
            String directorQoute = movies.getText();
            //if current id is found, update movie
            if (director.updateDirector(directorId, directorName, directorBDate, directorQoute)) {
                //set updated value on table row
                model.setValueAt(directorId, directorTable.getSelectedRow(), 0);
                model.setValueAt(directorName, directorTable.getSelectedRow(), 1);
                model.setValueAt(directorBDate, directorTable.getSelectedRow(), 2);
                model.setValueAt(directorQoute, directorTable.getSelectedRow(), 3);
                JOptionPane.showMessageDialog(null, "Updated Successfully!");

                //reset field
                clearField();
            } else {

                JOptionPane.showMessageDialog(null, "Update failed!");
            }
        }

    }//GEN-LAST:event_updateDirectorBtnActionPerformed

    private void deleteDirectorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDirectorBtnActionPerformed
        int dialogResult = JOptionPane.showConfirmDialog(null, "Delete a Director?", "Confirmation", JOptionPane.YES_NO_OPTION);

        model = (DefaultTableModel) directorTable.getModel();

        if (directorTable.getSelectedRowCount() == 1) {
            if (dialogResult == JOptionPane.YES_OPTION) {
                // User clicked "Yes"
                model.removeRow(directorTable.getSelectedRow());

                JOptionPane.showMessageDialog(null, "Deleted successfully!");
            } else {
                // User clicked "No" or closed the dialog
                System.out.println("Director not deleted");
            }

        } else {
            //if table has no data
            if (directorTable.getSelectedRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "Table is empty!");
                //if no row selected
            } else {
                JOptionPane.showMessageDialog(null, "Please select single row to delete!");
            }
        }
    }//GEN-LAST:event_deleteDirectorBtnActionPerformed

    private void directorTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_directorTableMouseClicked
        model = (DefaultTableModel) directorTable.getModel();

        //set data to text field when selected
        String tableName = model.getValueAt(directorTable.getSelectedRow(), 1).toString();
        String tableBirthDate = model.getValueAt(directorTable.getSelectedRow(), 2).toString();
        String tableMovie = model.getValueAt(directorTable.getSelectedRow(), 3).toString();

        //set to text field
        name.setText(tableName);
        dateOfBirth.setText(tableBirthDate);
        movies.setText(tableMovie);
    }//GEN-LAST:event_directorTableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        name.setText("");
        dateOfBirth.setText("");
        movies.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        directorTable.clearSelection();
    }//GEN-LAST:event_jButton1MouseClicked
    private void displayTable() {
        Object[] data = director.displayDirector();
        model = (DefaultTableModel) directorTable.getModel();
        model.addRow(data);
    }

    private void clearField() {
        name.setText("");
        dateOfBirth.setText("");
        movies.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDirectorBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField dateOfBirth;
    private javax.swing.JButton deleteDirectorBtn;
    private javax.swing.JTable directorTable;
    private javax.swing.JLabel fnLbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lnLbl;
    private javax.swing.JLabel miLbl;
    private javax.swing.JTextField movies;
    private javax.swing.JTextField name;
    private javax.swing.JButton updateDirectorBtn;
    // End of variables declaration//GEN-END:variables
}
